import { useState, useEffect } from 'react';
import { Sparkles, ChevronDown, ChevronUp, Loader2 } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import api from '../services/api';
import './AISummary.css';

const AISummary = ({ bookId }) => {
    const [isOpen, setIsOpen] = useState(false);
    const [summary, setSummary] = useState(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);
    const [fetched, setFetched] = useState(false);

    // Fetch the summary when the accordion is first opened
    // The GET endpoint auto-generates if not cached, so we always get a result
    useEffect(() => {
        if (!isOpen || fetched || !bookId) return;

        const fetchSummary = async () => {
            setLoading(true);
            setError(null);
            try {
                const res = await api.get(`/books/${bookId}/summary`);
                setSummary(res.data);
            } catch (err) {
                setError('Failed to load summary. Please try again.');
                console.error('Error fetching summary:', err);
            } finally {
                setLoading(false);
                setFetched(true);
            }
        };

        fetchSummary();
    }, [isOpen, fetched, bookId]);

    return (
        <div className="ai-summary-card">
            <button
                className={`ai-summary-header ${isOpen ? 'active' : ''}`}
                onClick={() => setIsOpen(!isOpen)}
            >
                <div className="ai-title">
                    <Sparkles className="ai-icon" size={20} />
                    <span>AI Summary</span>
                </div>
                {isOpen ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
            </button>

            <AnimatePresence>
                {isOpen && (
                    <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.3 }}
                        className="ai-summary-content"
                    >
                        <div className="ai-content-inner">
                            {loading && (
                                <div className="ai-loading">
                                    <Loader2 className="ai-spinner" size={20} />
                                    <span>Generating AI summary…</span>
                                </div>
                            )}

                            {error && (
                                <div className="ai-error">
                                    <p>{error}</p>
                                </div>
                            )}

                            {!loading && !error && summary && (
                                <div className="ai-highlight">
                                    <p>{summary.summary || summary.content || summary}</p>
                                    <p className="ai-tag">Generated by BookMind AI</p>
                                </div>
                            )}
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
};

export default AISummary;
